ar_layers: &id001
- 256
- 128
- 128
- 256
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: 10
  n_lags: 504
  reg_lambda: 0.001
config_events: null
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - &id003 !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 874108800000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 871948800000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          AAAAAADryEA=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          AAAAAADWxkA=
  global_normalization: true
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - __df__
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - *id003
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAADryEA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                AAAAAADWxkA=
  normalize: auto
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  daily_global_local: auto
  global_local: global
  mode: multiplicative
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 365.25
        resolution: 6
  reg_lambda: 0.01
  seasonality_local_reg: false
  weekly_arg: false
  weekly_global_local: auto
  yearly_arg: true
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 32
  epochs: 100
  lambda_delay: 50
  learning_rate: 0.003
  loss_func: !!python/object:torch.nn.modules.loss.MSELoss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: {}
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: {}
    _non_persistent_buffers_set: !!set {}
    _parameters: {}
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    reduction: none
    training: true
  loss_func_name: MSELoss
  lr_finder_args: {}
  n_data: 6473
  newer_samples_start: 0
  newer_samples_weight: 1.5
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: false
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.8
  growth: discontinuous
  n_changepoints: 320
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 5.0e-06
  trend_reg_threshold: null
id_list:
- __df__
lagged_reg_layers: []
max_lags: 504
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 252
n_lags: 504
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
